language: node_js
# When changing node version also update it on lines 31 and 49.
node_js:
  - "8"

sudo: false

cache:
  directories:
    - node_modules

env:
  - DB_HOST=localhost DB_PORT=2369 DB_USER=test DB_NAME=microauth DB_PASSWORD='' SERVER_PORT=8000
